import {
  UserProfile,
  Subject,
  DocumentItem,
  Quiz,
  QuizAttempt,
  Flashcard,
  StudyPlan,
  CalendarEvent,
  KnowledgeNode,
  ExamRadarData,
  LibraryResource,
  NotificationItem,
  VivaSession,
} from '../types';

export const DEMO_USER: UserProfile = {
  id: 'alex_demo_01',
  name: 'Alex Mercer',
  email: 'alex.mercer@university.edu',
  degree: 'B.Tech Computer Science & Engineering',
  college: 'Apex Institute of Technology & Science',
  branch: 'Computer Science & AI',
  semester: 'Semester 6',
  studyGoal: 'score_high',
  dailyHours: 3.5,
  learningStyle: 'interactive',
  streakDays: 9,
  totalStudyHours: 48.5,
  academicScore: 88,
  level: 7,
  xp: 3450,
  isCrackModeActive: false,
  crackModeExamName: 'DBMS University Semester Final',
  crackModeDaysRemaining: 5,
  isAdmin: false,
  createdAt: '2026-01-15T00:00:00.000Z',
};

export const DEMO_SUBJECTS: Subject[] = [
  {
    id: 'sub_dbms',
    name: 'Database Management Systems (DBMS)',
    code: 'CS601',
    semester: 'Semester 6',
    examDate: '2026-08-28',
    masteryPercentage: 74,
    syllabusCoverage: 85,
    color: '#8B5CF6',
    icon: 'Database',
    units: [
      {
        unitNumber: 1,
        title: 'ER Modeling & Relational Algebra',
        topics: ['Entity Relationship Diagrams', 'Relational Calculus', 'Integrity Constraints'],
        isCompleted: true,
      },
      {
        unitNumber: 2,
        title: 'SQL & Advanced Query Processing',
        topics: ['Nested Queries & Joins', 'Views & Triggers', 'Query Optimization Trees'],
        isCompleted: true,
      },
      {
        unitNumber: 3,
        title: 'Normalization & Schema Refinement',
        topics: ['1NF, 2NF, 3NF', 'Boyce-Codd Normal Form (BCNF)', 'Multi-valued Dependencies (4NF)'],
        isCompleted: false,
      },
      {
        unitNumber: 4,
        title: 'Transaction Management & Concurrency',
        topics: ['ACID Properties', 'Serializability & Precedence Graphs', 'Two-Phase Locking (2PL)', 'Deadlock Handling'],
        isCompleted: false,
      },
      {
        unitNumber: 5,
        title: 'Storage & Indexing',
        topics: ['B+ Trees', 'Hashing Techniques', 'RAID Architectures'],
        isCompleted: true,
      },
    ],
    weakTopics: ['Transactions & 2PL', 'BCNF Decomposition Proofs'],
    strongTopics: ['SQL Joins', 'ER Modeling', 'B+ Trees'],
  },
  {
    id: 'sub_os',
    name: 'Operating Systems',
    code: 'CS602',
    semester: 'Semester 6',
    examDate: '2026-09-02',
    masteryPercentage: 82,
    syllabusCoverage: 90,
    color: '#06B6D4',
    icon: 'Cpu',
    units: [
      { unitNumber: 1, title: 'Process Management & Scheduling', topics: ['Process States', 'CPU Scheduling Algorithms', 'IPC & Pipes'], isCompleted: true },
      { unitNumber: 2, title: 'Synchronization & Deadlocks', topics: ['Semaphores & Mutex', "Banker's Algorithm", 'Dining Philosophers Problem'], isCompleted: true },
      { unitNumber: 3, title: 'Memory Management', topics: ['Paging & Segmentation', 'Virtual Memory', 'Page Replacement (LRU/FIFO)'], isCompleted: false },
      { unitNumber: 4, title: 'File & Disk Management', topics: ['File Systems', 'Disk Scheduling (SCAN, C-LOOK)'], isCompleted: true },
    ],
    weakTopics: ['Page Replacement Algorithms', 'Deadlock Detection Proofs'],
    strongTopics: ['CPU Scheduling (Round Robin)', 'Process Synchronization'],
  },
  {
    id: 'sub_ml',
    name: 'Machine Learning & AI',
    code: 'CS603',
    semester: 'Semester 6',
    examDate: '2026-09-08',
    masteryPercentage: 68,
    syllabusCoverage: 75,
    color: '#10B981',
    icon: 'Brain',
    units: [
      { unitNumber: 1, title: 'Supervised Learning', topics: ['Linear & Logistic Regression', 'Decision Trees', 'SVM & Kernels'], isCompleted: true },
      { unitNumber: 2, title: 'Unsupervised Learning', topics: ['K-Means Clustering', 'PCA & Dimensionality Reduction'], isCompleted: false },
      { unitNumber: 3, title: 'Neural Networks & Deep Learning', topics: ['Backpropagation', 'Activation Functions', 'CNN Basics'], isCompleted: false },
    ],
    weakTopics: ['Backpropagation Gradient Derivations', 'SVM Dual Formulation'],
    strongTopics: ['Decision Trees', 'K-Means Clustering'],
  },
  {
    id: 'sub_dsa',
    name: 'Advanced Data Structures & Algorithms',
    code: 'CS604',
    semester: 'Semester 6',
    examDate: '2026-09-14',
    masteryPercentage: 89,
    syllabusCoverage: 95,
    color: '#F59E0B',
    icon: 'Binary',
    units: [
      { unitNumber: 1, title: 'Tree & Graph Algorithms', topics: ['AVL & Red-Black Trees', "Dijkstra's & Floyd Warshall", 'Disjoint Set Union'], isCompleted: true },
      { unitNumber: 2, title: 'Dynamic Programming', topics: ['Knapsack Problems', 'LCS & LIS', 'Matrix Chain Multiplication'], isCompleted: true },
      { unitNumber: 3, title: 'NP-Completeness', topics: ['Turing Reductions', '3-SAT to Vertex Cover'], isCompleted: false },
    ],
    weakTopics: ['NP-Complete Reductions'],
    strongTopics: ['Dynamic Programming', 'Graph Shortest Paths'],
  },
];

export const DEMO_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_1',
    title: 'DBMS_University_Complete_Notes_Unit1-5.pdf',
    subjectId: 'sub_dbms',
    subjectName: 'Database Management Systems (DBMS)',
    type: 'notes',
    fileSize: '4.8 MB',
    pageCount: 142,
    uploadDate: '2026-08-10',
    summary: 'Comprehensive lecture notes compiled from Prof. Korth & Navathe database curriculum. Covers functional dependencies, Armstrong axioms, conflict serializability, 2PL, and relational queries.',
    keyFormulas: [
      { term: 'Functional Dependency', definition: 'X → Y means identical X values imply identical Y values.', importance: 'Critical' },
      { term: 'BCNF Test', definition: 'For every non-trivial X → Y, X must be a superkey of relation R.', importance: 'Critical' },
      { term: 'Serializability Test', definition: 'A schedule is conflict serializable iff its precedence graph has no directed cycles.', importance: 'High' },
    ],
    coreConcepts: [
      { name: 'Schema Decomposition', description: 'Decomposing tables to eliminate insertion and update anomalies without losing dependencies.', pageReference: 'Pages 34–48' },
      { name: 'Concurrency Lock Modes', description: 'Shared (S) for read access and Exclusive (X) for write access under strict 2PL.', pageReference: 'Pages 78–92' },
    ],
    predictedExamQuestions: [
      { question: 'Define BCNF. How does it differ from 3NF? Prove with an example relation.', marks: 10, frequencyProb: '94%' },
      { question: 'Check if Schedule S: r1(x) r2(x) w1(x) w2(y) c1 c2 is conflict serializable.', marks: 6, frequencyProb: '88%' },
    ],
    tags: ['DBMS', 'Semester Exam', 'Normalization', 'Transactions'],
    isAnalyzed: true,
    isBookmarked: true,
  },
  {
    id: 'doc_2',
    title: 'DBMS_Previous_5_Years_Question_Papers_Solved.pdf',
    subjectId: 'sub_dbms',
    subjectName: 'Database Management Systems (DBMS)',
    type: 'pyq',
    fileSize: '6.2 MB',
    pageCount: 68,
    uploadDate: '2026-08-12',
    summary: 'Past 5 years solved university question papers with marked answer key and recurring topic patterns. Essential for Exam Radar prediction.',
    tags: ['PYQ', 'Solved Papers', 'Exam Radar', 'DBMS'],
    isAnalyzed: true,
    isBookmarked: true,
  },
  {
    id: 'doc_3',
    title: 'Operating_Systems_Silberschatz_Key_Concepts.pdf',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    type: 'textbook',
    fileSize: '8.1 MB',
    pageCount: 210,
    uploadDate: '2026-08-05',
    summary: 'Extracted chapter summaries of Process Synchronization, Banker algorithm, Deadlock avoidance, and Page Replacement policies.',
    tags: ['OS', 'Semaphores', 'Deadlocks', 'Paging'],
    isAnalyzed: true,
  },
];

export const DEMO_EXAM_RADAR_DBMS: ExamRadarData = {
  subject: 'Database Management Systems (DBMS)',
  confidenceScore: 94,
  topPriorityTopics: [
    {
      topic: 'SQL Joins, Subqueries & Group By Aggregations',
      priorityScore: 92,
      frequency: 'High (Appeared in 5 of last 5 years)',
      marksWeightage: '16–20 Marks',
      typicalQuestionType: 'Query formulation + Relational algebra tree translation',
      strategicReason: 'Always appears as compulsory questions in Section B. High scoring if practiced well.',
    },
    {
      topic: 'Normalization & BCNF Decomposition Proofs',
      priorityScore: 86,
      frequency: 'High (Appeared in 4 of last 5 years)',
      marksWeightage: '12–16 Marks',
      typicalQuestionType: 'Finding candidate keys from FDs & verifying Lossless Join',
      strategicReason: 'Standard theoretical anchor. Examiners test canonical cover & minimal key calculation.',
    },
    {
      topic: 'Transactions, ACID & Concurrency Control (2PL)',
      priorityScore: 78,
      frequency: 'Medium-High (Appeared in 4 of last 5 years)',
      marksWeightage: '10–14 Marks',
      typicalQuestionType: 'Schedule conflict serializability graph + Lock hierarchy',
      strategicReason: 'High discriminator topic where students often lose marks on dirty reads and phantom rows.',
    },
    {
      topic: 'B+ Tree Index Insertion & Node Splitting',
      priorityScore: 68,
      frequency: 'Medium (Appeared in 3 of last 5 years)',
      marksWeightage: '8–10 Marks',
      typicalQuestionType: 'Step-by-step key insertion into B+ tree of order 4',
      strategicReason: '100% predictable algorithm question. Guarantees full marks if tracing steps are memorized.',
    },
    {
      topic: 'ER Model to Relational Table Mapping',
      priorityScore: 54,
      frequency: 'Regular (Appeared in 2 of last 5 years)',
      marksWeightage: '6–10 Marks',
      typicalQuestionType: 'Constructing ER schema with total participation and weak entities',
      strategicReason: 'Standard opening question in Part A.',
    },
  ],
  unitDistribution: [
    { unit: 'Unit 1: ER & Relational Algebra', percentage: 20 },
    { unit: 'Unit 2: SQL & Query Processing', percentage: 28 },
    { unit: 'Unit 3: Normalization (1NF-BCNF)', percentage: 24 },
    { unit: 'Unit 4: Transactions & Concurrency', percentage: 18 },
    { unit: 'Unit 5: Indexing & Storage', percentage: 10 },
  ],
  highProbabilityQuestions: [
    'Define ACID properties and explain why Durability requires Write-Ahead Logging (WAL) (8 Marks).',
    'Given R(A, B, C, D, E) with F = {A → BC, CD → E, B → D, E → A}, compute candidate keys and decompose into BCNF (10 Marks).',
    'Determine if the schedule S: r1(A); r2(A); w1(B); w2(A); c1; c2 is conflict serializable using precedence graph (6 Marks).',
    'Differentiate between Dense and Sparse B+ Tree indexing with diagrams (6 Marks).',
  ],
  expertAdvice: 'Prioritize SQL query writing and 3NF/BCNF decomposition proofs. Mastering these two units guarantees at least 45% of your total exam score.',
};

export const DEMO_KNOWLEDGE_NODES: KnowledgeNode[] = [
  { id: 'kn_1', subject: 'DBMS', unit: 'Unit 2', topic: 'SQL Joins & Group By', masteryStatus: 'strong', masteryPercentage: 92, lastTestedScore: 95, recommendedAction: 'Maintain mastery with 5-question weekly drill.' },
  { id: 'kn_2', subject: 'DBMS', unit: 'Unit 1', topic: 'ER Modeling & Relational Schema', masteryStatus: 'strong', masteryPercentage: 88, lastTestedScore: 90, recommendedAction: 'Ready for exam.' },
  { id: 'kn_3', subject: 'DBMS', unit: 'Unit 5', topic: 'B+ Tree Indexing & Search', masteryStatus: 'moderate', masteryPercentage: 72, lastTestedScore: 70, recommendedAction: 'Practice node split corner cases.' },
  { id: 'kn_4', subject: 'DBMS', unit: 'Unit 3', topic: 'Normalization & BCNF Proofs', masteryStatus: 'weak', masteryPercentage: 58, lastTestedScore: 60, recommendedAction: 'Review canonical cover calculation.' },
  { id: 'kn_5', subject: 'DBMS', unit: 'Unit 4', topic: 'Transactions & Concurrency (2PL)', masteryStatus: 'critical', masteryPercentage: 42, lastTestedScore: 40, recommendedAction: '🚨 Critical Weak Area! Schedule 45m immediate revision.' },
  { id: 'kn_6', subject: 'Operating Systems', unit: 'Unit 1', topic: 'CPU Scheduling (Round Robin/SJF)', masteryStatus: 'strong', masteryPercentage: 94, lastTestedScore: 100, recommendedAction: 'Mastered.' },
  { id: 'kn_7', subject: 'Operating Systems', unit: 'Unit 2', topic: 'Semaphores & Dining Philosophers', masteryStatus: 'moderate', masteryPercentage: 76, lastTestedScore: 75, recommendedAction: 'Revise lock race conditions.' },
  { id: 'kn_8', subject: 'Operating Systems', unit: 'Unit 3', topic: 'Page Replacement Algorithms (LRU)', masteryStatus: 'weak', masteryPercentage: 52, lastTestedScore: 50, recommendedAction: 'Practice LRU vs Belady anomaly numericals.' },
];

export const DEMO_STUDY_PLAN: StudyPlan = {
  id: 'plan_current_01',
  modeName: '🎯 Adaptive Mastery Roadmap',
  targetExam: 'Database Management Systems (DBMS)',
  daysRemaining: 12,
  dailyHours: 3.5,
  isCrackMode: false,
  todayTasks: [
    {
      id: 'task_1',
      subject: 'DBMS',
      topic: 'Transactions & 2PL Concurrency Control',
      durationMinutes: 45,
      type: 'concept_revision',
      difficulty: 'High',
      reason: 'Flagged as Critical Weak Area from recent diagnostic quiz.',
      isCompleted: false,
    },
    {
      id: 'task_2',
      subject: 'DBMS',
      topic: 'BCNF Decomposition & Lossless Join Proofs',
      durationMinutes: 35,
      type: 'practice_quiz',
      difficulty: 'Medium',
      reason: 'Top 86% high-yield recurring topic in Exam Radar.',
      isCompleted: false,
    },
    {
      id: 'task_3',
      subject: 'DBMS',
      topic: '15 Spaced Repetition Flashcards Drill',
      durationMinutes: 15,
      type: 'flashcards',
      difficulty: 'Easy',
      reason: 'Memory retention reinforcement.',
      isCompleted: true,
    },
    {
      id: 'task_4',
      subject: 'Operating Systems',
      topic: 'Virtual Memory & LRU Page Replacement',
      durationMinutes: 30,
      type: 'concept_revision',
      difficulty: 'Medium',
      reason: 'Scheduled secondary subject progress.',
      isCompleted: false,
    },
  ],
  weeklyRoadmap: [
    { day: 'Monday', focus: 'DBMS: Normalization & BCNF Decomposition proofs', hours: 3.5 },
    { day: 'Tuesday', focus: 'DBMS: Transactions, ACID, Serializability Precedence graphs', hours: 3.5 },
    { day: 'Wednesday', focus: 'OS: Semaphores, Deadlock Avoidance (Banker Algorithm)', hours: 3.0 },
    { day: 'Thursday', focus: 'DBMS: B+ Tree Indexing & Past 3 Years Solved Papers', hours: 4.0 },
    { day: 'Friday', focus: 'AI & Machine Learning: Backpropagation gradient traces', hours: 3.5 },
    { day: 'Saturday', focus: 'Full 3-Hour AI Mock Exam Simulator (DBMS)', hours: 4.5 },
    { day: 'Sunday', focus: 'Weak Area Targeted Retest + Viva Simulation Room', hours: 3.0 },
  ],
  crackTip: '💡 Focus on Section B 10-mark questions first. Solving 2 multi-part Normalization proofs gives you instant confidence.',
  updatedAt: '2026-08-16T08:00:00.000Z',
};

export const DEMO_FLASHCARDS: Flashcard[] = [
  {
    id: 'fc_1',
    deckId: 'deck_dbms_acid',
    subjectId: 'sub_dbms',
    subjectName: 'DBMS',
    topic: 'Transactions',
    front: 'What does the "A" in ACID stand for and what is its core invariant?',
    back: 'Atomicity: Guarantees "all-or-nothing" execution. If any operation within the transaction fails, the entire transaction is rolled back.',
    difficulty: 'easy',
    reviewCount: 4,
    isMastered: true,
  },
  {
    id: 'fc_2',
    deckId: 'deck_dbms_norm',
    subjectId: 'sub_dbms',
    subjectName: 'DBMS',
    topic: 'Normalization',
    front: 'What is the strict mathematical definition of BCNF (Boyce-Codd Normal Form)?',
    back: 'A relation R is in BCNF iff for every non-trivial functional dependency X → Y holding in R, X is a superkey of R.',
    difficulty: 'medium',
    reviewCount: 3,
    isMastered: false,
  },
  {
    id: 'fc_3',
    deckId: 'deck_dbms_locks',
    subjectId: 'sub_dbms',
    subjectName: 'DBMS',
    topic: 'Concurrency',
    front: 'How does Strict 2PL differ from Rigorous 2PL in database systems?',
    back: 'Strict 2PL holds all Exclusive (X) locks until commit/abort. Rigorous 2PL holds BOTH Shared (S) and Exclusive (X) locks until transaction completion.',
    difficulty: 'hard',
    reviewCount: 2,
    isMastered: false,
  },
  {
    id: 'fc_4',
    deckId: 'deck_os_sched',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    topic: 'Scheduling',
    front: 'What is Convoy Effect in CPU scheduling?',
    back: 'A phenomenon in FCFS where short CPU-burst processes are delayed behind a long CPU-burst process, leading to low CPU and device utilization.',
    difficulty: 'easy',
    reviewCount: 5,
    isMastered: true,
  },
  {
    id: 'fc_5',
    deckId: 'deck_os_deadlock',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    topic: 'Deadlocks',
    front: 'Name the 4 Coffman conditions required simultaneously for a deadlock to occur.',
    back: '1. Mutual Exclusion\n2. Hold and Wait\n3. No Preemption\n4. Circular Wait',
    difficulty: 'medium',
    reviewCount: 4,
    isMastered: true,
  },
];

export const DEMO_QUIZZES: Quiz[] = [
  {
    id: 'quiz_dbms_diag',
    title: 'DBMS Comprehensive Exam Readiness Diagnostic',
    subjectId: 'sub_dbms',
    subjectName: 'DBMS',
    topic: 'Transactions & Normalization',
    difficulty: 'adaptive',
    durationMinutes: 15,
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        question: 'Which ACID property requires Write-Ahead Logging (WAL) to survive unexpected system power failures?',
        options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
        correctIndex: 3,
        explanation: 'Durability ensures that once a transaction commits, its changes survive crashes. WAL guarantees logs are flushed before dirty buffer pages.',
        topic: 'Transactions',
        difficulty: 'medium',
        marks: 2,
      },
      {
        id: 'q2',
        type: 'mcq',
        question: 'If relation R(A, B, C) has functional dependencies {A → B, B → C}, in which normal form is R if candidate key is A?',
        options: ['1NF only', '2NF but not 3NF', '3NF but not BCNF', 'BCNF'],
        correctIndex: 1,
        explanation: 'R is in 2NF because all non-prime attributes (B, C) depend on full candidate key A. But B → C represents a transitive dependency on non-prime attribute B, violating 3NF.',
        topic: 'Normalization',
        difficulty: 'medium',
        marks: 2,
      },
      {
        id: 'q3',
        type: 'mcq',
        question: 'In Two-Phase Locking (2PL), once a transaction releases its first lock, which phase does it enter?',
        options: ['Growing Phase', 'Shrinking Phase', 'Validation Phase', 'Commit Phase'],
        correctIndex: 1,
        explanation: 'In the Shrinking Phase, a transaction may release locks but cannot acquire any new locks, ensuring serializability.',
        topic: 'Concurrency Control',
        difficulty: 'easy',
        marks: 2,
      },
      {
        id: 'q4',
        type: 'mcq',
        question: 'What is the maximum number of pointers in a B+ Tree node of order p?',
        options: ['p - 1', 'p', '2p', 'p / 2'],
        correctIndex: 1,
        explanation: 'A B+ Tree internal node of order p contains at most p pointers (child references) and p - 1 search keys.',
        topic: 'Indexing',
        difficulty: 'hard',
        marks: 3,
      },
      {
        id: 'q5',
        type: 'mcq',
        question: 'Which SQL operator is used to test for non-empty subquery results efficiently without retrieving all rows?',
        options: ['IN', 'EXISTS', 'HAVING', 'ANY'],
        correctIndex: 1,
        explanation: 'EXISTS terminates scanning as soon as the first matching record in the subquery is found, optimizing execution time.',
        topic: 'SQL Mastery',
        difficulty: 'easy',
        marks: 2,
      },
    ],
    isMockExam: false,
    createdAt: '2026-08-14T10:00:00.000Z',
  },
];

export const DEMO_QUIZ_ATTEMPTS: QuizAttempt[] = [
  {
    id: 'att_1',
    quizId: 'quiz_dbms_diag',
    quizTitle: 'DBMS Comprehensive Exam Readiness Diagnostic',
    subjectName: 'DBMS',
    score: 8,
    totalMarks: 11,
    accuracyPercentage: 73,
    userAnswers: { q1: 3, q2: 1, q3: 1, q4: 0, q5: 1 },
    timeSpentSeconds: 420,
    weakTopicsIdentified: ['B+ Tree Node Sizing & Order Calculation'],
    strongTopicsIdentified: ['ACID Durability', 'Normalization 2NF/3NF', 'Two-Phase Locking'],
    completedAt: '2026-08-15T16:30:00.000Z',
  },
];

export const DEMO_VIVA_SESSION: VivaSession = {
  id: 'viva_demo_01',
  type: 'university',
  subjectName: 'Database Management Systems',
  topicOrProjectTitle: 'Transactions & Recovery Mechanics',
  questions: [
    {
      id: 'vq_1',
      question: 'Professor Examiner: Alex, explain why database systems need Write-Ahead Logging instead of directly updating disk blocks upon commit.',
      studentAnswer: 'Because disk writes are slow and if power fails mid-write, the database is corrupted. WAL writes the log records sequentially to disk first so recovery can redo or undo operations.',
      score: 88,
      feedback: 'Excellent answer. You correctly noted sequential write performance and crash recovery resilience.',
    },
    {
      id: 'vq_2',
      question: 'Professor Examiner: What is a Dirty Read, and which SQL transaction isolation level permits it?',
      studentAnswer: 'A dirty read is when a transaction reads uncommitted changes from another transaction that might rollback. READ UNCOMMITTED permits it.',
      score: 95,
      feedback: 'Spot on precision with isolation level naming.',
    },
  ],
  overallReport: {
    score: 88,
    verdict: 'Strong Conceptual Master',
    strengths: ['Clear definition of WAL mechanism', 'Exact knowledge of ANSI SQL isolation levels'],
    improvements: ['Include the name of the ARIES recovery algorithm for bonus points', 'Cite 2PL locking protocols'],
    idealAnswer: 'The candidate demonstrated above-average university viva readiness. Retain the same speed and confidence during the oral panel.',
  },
  completedAt: '2026-08-15T18:00:00.000Z',
};

export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  { id: 'ev_1', title: 'DBMS Semester Examination (CS601)', subject: 'DBMS', date: '2026-08-28', time: '10:00 AM - 01:00 PM', type: 'exam', priority: 'high' },
  { id: 'ev_2', title: 'Operating Systems University Exam (CS602)', subject: 'OS', date: '2026-09-02', time: '10:00 AM - 01:00 PM', type: 'exam', priority: 'high' },
  { id: 'ev_3', title: 'DBMS Lab Project Viva & Submission', subject: 'DBMS', date: '2026-08-24', time: '02:00 PM', type: 'viva', priority: 'high' },
  { id: 'ev_4', title: 'DBMS Mock Exam Simulation 1', subject: 'DBMS', date: '2026-08-22', time: '04:00 PM', type: 'study_session', priority: 'medium' },
  { id: 'ev_5', title: 'ML Mini-Project Code Review', subject: 'Machine Learning', date: '2026-08-26', time: '11:00 AM', type: 'assignment', priority: 'medium' },
];

export const DEMO_LIBRARY_RESOURCES: LibraryResource[] = [
  {
    id: 'lib_1',
    title: 'Database System Concepts (Open Edition Compendium)',
    author: 'Silberschatz, Korth, Sudarshan & Open Academic Consortium',
    category: 'Computer Science',
    subject: 'DBMS',
    difficulty: 'Intermediate',
    pages: 340,
    fileFormat: 'PDF / Interactive',
    description: 'Gold standard university textbook companion on relational data models, SQL queries, transaction management, distributed databases, and index structures.',
    tags: ['DBMS', 'OpenCourseWare', 'Relational Model', 'Transactions'],
    license: 'Creative Commons CC-BY-NC 4.0 / Public Domain Academic Edition',
    sourceUrl: 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/',
    coverGradient: 'from-purple-600 via-indigo-700 to-slate-900',
    isBookmarked: true,
  },
  {
    id: 'lib_2',
    title: 'Operating Systems: Three Easy Pieces (OSTEP Free Edition)',
    author: 'Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau',
    category: 'Computer Science',
    subject: 'Operating Systems',
    difficulty: 'Intermediate',
    pages: 412,
    fileFormat: 'PDF / Text',
    description: 'Renowned textbook organized around the three fundamental concepts of operating systems: Virtualization, Concurrency, and Persistence.',
    tags: ['OS', 'Virtualization', 'Concurrency', 'Paging', 'Open Access'],
    license: 'Free Educational Web Distribution / Open Access Authorized',
    sourceUrl: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
    coverGradient: 'from-cyan-600 via-blue-700 to-slate-900',
    isBookmarked: true,
  },
  {
    id: 'lib_3',
    title: 'Introduction to Algorithms & Dynamic Programming Notes',
    author: 'MIT OpenCourseWare (EECS Department)',
    category: 'Computer Science',
    subject: 'Algorithms',
    difficulty: 'Advanced',
    pages: 280,
    fileFormat: 'PDF / Notes',
    description: 'Detailed analysis of asymptotic runtimes, divide-and-conquer recurrences, graph traversal, greedy invariants, and dynamic programming state design.',
    tags: ['Algorithms', 'MIT OCW', 'Dynamic Programming', 'NP-Complete'],
    license: 'MIT OpenCourseWare CC-BY-NC-SA',
    sourceUrl: 'https://ocw.mit.edu',
    coverGradient: 'from-amber-500 via-orange-600 to-slate-900',
    isBookmarked: false,
  },
  {
    id: 'lib_4',
    title: 'Mathematics for Machine Learning & Data Science',
    author: 'Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong',
    category: 'AI & Data Science',
    subject: 'Machine Learning',
    difficulty: 'Intermediate',
    pages: 390,
    fileFormat: 'PDF / Open Textbook',
    description: 'Linear algebra, analytic geometry, matrix decompositions, vector calculus, optimization, and probability theory for machine learning.',
    tags: ['Math', 'Linear Algebra', 'Machine Learning', 'Calculus'],
    license: 'Cambridge Open Access / Legal Educational Use',
    sourceUrl: 'https://mml-book.github.io',
    coverGradient: 'from-emerald-500 via-teal-700 to-slate-900',
    isBookmarked: true,
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    title: '🚨 Exam Radar Alert: DBMS High-Yield Warning',
    message: 'Your DBMS exam is 12 days away. Normalization and 2PL account for ~35 marks in past papers. We have queued these in Today’s Mission.',
    type: 'exam_alert',
    timestamp: '10 minutes ago',
    isRead: false,
    actionUrl: 'study',
  },
  {
    id: 'notif_2',
    title: '🔥 9-Day Study Streak Unlocked!',
    message: 'You have maintained your study momentum for 9 continuous days. XP +150 awarded.',
    type: 'streak',
    timestamp: '2 hours ago',
    isRead: false,
  },
  {
    id: 'notif_3',
    title: '🎯 Daily Mission Generated',
    message: 'Today’s AI adaptive mission is ready: 4 tasks (~105 mins). Ready to crack your exam?',
    type: 'daily_mission',
    timestamp: '6 hours ago',
    isRead: true,
    actionUrl: 'study',
  },
  {
    id: 'notif_4',
    title: '⚠️ Weak Topic Alert',
    message: 'Recent diagnostic quiz identified "Transactions & Concurrency" as a critical weak area (42% mastery). Revision task created.',
    type: 'weak_topic',
    timestamp: '1 day ago',
    isRead: true,
    actionUrl: 'study',
  },
];
